# action.yml
name: 'Apex FTP download'
description: 'Download a world from Apex'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    FTP_HOST: ${{ inputs.ftpHost }}
    FTP_USER: ${{ inputs.ftpUser }}
    FTP_PASS: ${{ inputs.ftpPass }}
    WORLD: ${{ inputs.world }}
inputs:
  ftpHost:
    description: Host to download from
    required: true
  ftpUser:
    description: FTP username
    required: true
  ftpPass:
    description: FTP password
    required: true
  world:
    description: World folder to download
    required: false
    default: 'world'
