
name: Overviewer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine/git
      volumes: 
        - world:/home/minecraft/server
        - output:/home/minecraft/render
    env:
      MINECRAFT_VERSION: 1.15.2

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download world from Minecraft Realms
      uses: ./
      id: realms-download
      with:
        minecraftEmail: ${{ secrets.minecraftEmail }}
        minecraftPassword: ${{ secrets.minecraftPassword }}
    
    - name: Generate map from Minecraft world
      uses: docker://mide/minecraft-overviewer
