
name: Overviewer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '0 */6 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine/git
      volumes: 
        - $GITHUB_WORKSPACE:/workspace
    env:
      MINECRAFT_VERSION: 1.15.2

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download world from Minecraft Realms
      uses: ./actions/download
      id: realms-download
      with:
        minecraftEmail: ${{ secrets.minecraftEmail }}
        minecraftPassword: ${{ secrets.minecraftPassword }}
        slotNumber: 3
    
    - name: Generate map from Minecraft world
      uses: docker://mide/minecraft-overviewer

    - name: Deploy to  GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        build_dir: /home/minecraft/render
