
name: Overviewer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '0 */6 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine/git
    env:
      MINECRAFT_VERSION: 1.16.3

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download world from Apex FTP
      uses: ./actions/download
      id: apex-download
      with:
        ftpHost: 51.77.116.89
        ftpUser: quarterto.366291
        ftpPassword: ${{ secrets.ftpPassword }}
        world: 'this-land'

    - name: Download Minecraft client.jar
      uses: ./actions/textures
    
    - name: Generate map from Minecraft world
      uses: ./actions/overviewer

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        build_dir: ${{ github.workspace }}/render
