
name: Overviewer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
      volumes: 
        - world:/home/minecraft/server
        - output:/home/minecraft/render
    env:
      MINECRAFT_VERSION: 1.15.2

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download world from Minecraft Realms
      run: echo WIP
    
    - name: Generate map from Minecraft world
      uses: docker://mide/minecraft-overviewer
